# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26a632fea6c5137844e807f3f05252aebb73085e0813be002da4052447c2fdf2a98db2967595bde82e40100c747d3ae2f50beea78495f5fdde0fedf12c075719

test:
  secret_key_base: 6d02d72cdfc940b919df499ab0cf0dc04e4eb99173962a29b61384016ba215a72ed75c0dc15cf777726a2637bb87060d014444449b03fc777646d05c817c81f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
